# -*- coding: utf-8 -*-
"""Estatísticas de Rastreamento - GSC

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BxlNsFYLU7oe_pSFVa58wlOopmQjMOy_
"""

import plotly.graph_objects as go

# Dados
labels = ["Total de solicitações de rastreamento", "Tamanho total do download", "Média do tempo de resposta"]
values = [4.41, 131, 528]

# Criando o gráfico
fig = go.Figure(data=[
    go.Bar(name='Métricas', x=labels, y=values, text=values, textposition='auto')
])

# Ajustes visuais
fig.update_layout(
    title="Métricas de Rastreamento",
    xaxis_title="Métricas",
    yaxis_title="Valores",
    yaxis=dict(range=[0, max(values) * 1.1]),
)

fig.show()



import plotly.graph_objects as go

# Dados
categorias = ['Por resposta', 'Por tipo de arquivo', 'Por finalidade', 'Por tipo de Googlebot']
subcategorias = {
    'Por resposta': ['301', '200', '404', '302', '5XX'],
    'Por tipo de arquivo': ['HTML', 'JSON', 'JavaScript', 'Imagem', 'PDF'],
    'Por finalidade': ['Atualização', 'Detecção'],
    'Por tipo de Googlebot': ['Smartphone', 'Computador', 'Carregamento de recurso da página', 'AdsBot', 'Imagem']
}
percentuais = {
    'Por resposta': [48, 45, 5, 2, 1],
    'Por tipo de arquivo': [32, 12, 1, 1, 1],
    'Por finalidade': [94, 6],
    'Por tipo de Googlebot': [47, 25, 21, 5, 1]
}

# Criando o gráfico
fig = go.Figure()

# Adicionando as barras empilhadas
for categoria in categorias:
    for i, subcategoria in enumerate(subcategorias[categoria]):
        fig.add_trace(go.Bar(
            x=[categoria],
            y=[percentuais[categoria][i]],
            name=subcategoria,
            text=f'{subcategoria}: {percentuais[categoria][i]}%',
            textposition='auto'
        ))

# Ajustes visuais
fig.update_layout(
    barmode='stack',
    title='Detalhamento das Solicitações de Rastreamento',
    xaxis_title='Categorias',
    yaxis_title='Percentual',
    yaxis=dict(range=[0, 100]),
)

fig.show()